Get visitorId from localstorage
coveooss/sf-case-assist-cookbook pull request #7
Opened 2021-02-05 21:01 UTC by erocheleau

Get visitorId from localstorage

Added scratch org def settings

2021-02-05 22:20 UTC, ebouchard2 approved these changes

2021-02-08 15:03 UTC, lbergeron requested changes
Tests should be added to validate that `visitorId` is read from the storage.

2021-02-08 15:03 UTC, lbergeron commented on src/main/default/lwc/caseAssistFlow/caseAssistFlow.js
> +        const visitorId = localStorage.getItem('visitorId');
Can you add tests to validate that `visitorId` is read from the storage?

2021-02-08 15:18 UTC, louis-bompart reviewed
I think it'd be nice to change how we get the visitorId

2021-02-08 15:18 UTC, louis-bompart commented on src/main/default/lwc/caseAssistFlow/caseAssistFlow.js
> +        // If you have the AnalyticsBeacon LWC in your community, it will have generated a visitorId for you by now.
I think it'd make sense for the AnalyticsBeacon to have a method that uses the Storage class of CA.js
You can get the storage instance using `window.coveoanalytics.storage.getAvailableStorage()`

You could wrap this in a utility class (not a component) and then refer to this class and its function:
![image](https://user-images.githubusercontent.com/12366410/107239520-f0567000-69f6-11eb-8400-46b19235fde2.png)

2021-02-08 19:02 UTC, louis-bompart approved these changes

2021-02-08 19:26 UTC, lbergeron approved these changes

2021-02-08 19:27 UTC, merged